//a binary tree contains functions below:
//InitTree(&T)
//DestroyTree(&T)
//CreateTree(&T, definition)
//ClearTree(&T)
//TreeEmpty(T)
//TreeDepth(T)
//Root(T)
//return_Value(T, cur_e)
//Assign(&T, cur_e, value)
//return_Parent(T, cur_e)
//return_LeftChild(T, cur_e)
//return_RightChild(T, cur_e)
//return_RightSibling(T, cur_e)
//InsertChild(&T, p, i, c)
//DeleteChild(&T, p, i)
//TraverseTree(T, visit())